const projects = [
  {
    id: 'accurate-construction',
    siteLink: 'https://accurateconstruction.com.au',
    codeLink: 'https://github.com/LJ-WebDev/accurateconstruction',
    type: 'Client / Work',
    priority: 1,
    title: 'Accurate Construction',
    description:
      'Website for a construction business to advertise their services.',
    desktopImage: 'img/projects/accurate-construction-desktop.webp',
    mobileImage: 'img/projects/accurate-construction-mobile.png',
    imageAlt: 'Accurate Construction screenshot',
    tags: ['HTML', 'CSS', 'JS'],
    datePublished: 'Dec 2024',
  },
  {
    id: 'lj-music',
    siteLink: 'https://lj-music.netlify.app',
    codeLink: 'https://github.com/LJ-WebDev/lj-music-spa',
    type: 'Personal',
    priority: 2,
    title: 'LJ Music',
    description: 'Web SPA to gain experience with Vue and showcase my music.',
    tags: ['HTML', 'CSS', 'JavaScript', 'Vue.js', 'Tailwind'],
    desktopImage: 'img/projects/lj-music-desktop.webp',
    mobileImage: 'img/projects/lj-music-mobile.png',
    imageAlt: 'LJ Music screenshot',
    datePublished: 'Aug 2025',
  },
  {
    id: 'expense-tracker',
    siteLink: 'https://expense-tracker-261225.netlify.app',
    codeLink: 'https://github.com/LJ-WebDev/expenses-tracker',
    type: 'Personal \u2022 Tutorial-based',
    priority: 2,
    title: 'Expense Tracker',
    description: 'Offline-first expense tracking app using localStorage.',
    tags: ['HTML', 'CSS', 'JS', 'Vue.js', 'Tailwind'],
    desktopImage: 'img/projects/expense-tracker-desktop.webp',
    mobileImage: 'img/projects/expense-tracker-mobile.png',
    imageAlt: 'Expense Tracker screenshot',
    datePublished: 'Dec 2025',
  },
  {
    id: 'brightspark-electrical',
    siteLink: 'https://brightspark-electrical.netlify.app',
    codeLink:
      'https://github.com/LJ-WebDev/BrightSpark-Electrical---Demo-Project',
    type: 'Personal \u2022 Demo',
    priority: 2,
    title: 'Brightspark Electrical',
    description:
      'Demo project to practice the tagged tech. I used AI a lot for this one to do most of the designing and coding.',
    tags: ['HTML', 'CSS', 'JavaScript', 'Tailwind'],
    desktopImage: ['img/projects/brightspark-electrical-desktop.webp'],
    mobileImage: ['img/projects/brightspark-electrical-mobile.png'],
    imageAlt: 'BrightSpark Electrical screenshot',
    datePublished: 'Jan 2026',
  },
];
